# Generated by Django 4.2 on 2023-06-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cour',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('diff', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video_cour',
            fields=[
                ('type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title1', models.CharField(max_length=100)),
                ('description1', models.TextField()),
                ('video1', models.FileField(upload_to='videos/')),
                ('title2', models.CharField(max_length=100)),
                ('description2', models.TextField()),
                ('video2', models.FileField(upload_to='videos/')),
                ('title3', models.CharField(max_length=100)),
                ('description3', models.TextField()),
                ('video3', models.FileField(upload_to='videos/')),
                ('title4', models.CharField(max_length=100)),
                ('description4', models.TextField()),
                ('video4', models.FileField(upload_to='videos/')),
                ('title5', models.CharField(max_length=100)),
                ('description5', models.TextField()),
                ('video5', models.FileField(upload_to='videos/')),
                ('name_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.cour')),
            ],
        ),
    ]
