# Generated by Django 4.2 on 2023-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_cour'),
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameU', models.CharField(max_length=128)),
                ('emailU', models.EmailField(max_length=250)),
                ('passwordU', models.CharField(max_length=128)),
            ],
        ),
    ]
